README.md
`cleanOnExit()` is part of `helpers`, not `manifest`.
=> README: Fix typo in cleanOnExit section

src/helpers/choose-port.js, src/plugins.js, src/presets.js, src/presets.test.js
- Use `options` consistently when naming arguments, instead of `opts`.
- Fix ESLint issues
- Standardize alignment of JSDoc param syntax (all params aligned) and returns lines (not aligned with params)
=> Clean up lint issues and jsdoc comments

docs/guides/getting-started.md
=> Add Getting-Started guide

babel-preset.js
JavaScript-based Babel preset files will be executed over and over again, unless they dictate if and how they can be cached (see [`api.cache`](https://babeljs.io/docs/en/config-files#apicache)).
I was wondering if it makes sense to cache the preset (_forever_) as it doesn't include any dynamic things at all anyway...?
=> Allow for caching the Babel preset

src/presets.js
As discussed a while ago on Slack, this PR adds default values for both `entry` and `output.path`. If it **doesn't** work for anyone, they just have to specify whatever they need, which is just what they have to do right now to. If it **does** work for someone, they have less stuff to do. 🙂
I already updated some inline documentation, but maybe you also want to update some of the markdown files...?
=> Add default entry point and output path

src/helpers/file-path.js, src/helpers/file-path.test.js
The `filePath` test was only working with linux-style paths (or rather: directory separators).
For Windows, you would get something like this:
This PR includes the following:
* add custom Jest matcher that understands both linux and Windows paths (via a regular expression);
* add Windows path test case;
* manually import `process` in the `file-path.js` file so it can be mocked in the test.
=> Fix filePath test for Windows

src/presets.js, src/presets.test.js
I have been looking into using `React.lazy`, and async imports in order to break up large bundles. However I ran into an issue with the browser caching chunk files. 
The default `filename` setting is `[name].js`, with no hash. When used in conjunction with [HM Asset Loader](https://github.com/humanmade/asset-loader) this is fine - it adds the filemtime as a query param using the WordPress asset versioning arg.
But this isn't fine for chunk files. By default, `chunkFilename` is inferred from the `filename`, and thus when using webpack helpers, you will see files like `0.js` used for chunks. If the contents of the chunk changes, the browser may serve a cached chunk and things will fall over. 
If we specify a hash in the `chunkFilename` - it all works great!
=> Use content hash in chunk filename

package.json, src/helpers/file-path.test.js, src/presets.js, src/presets.test.js, src/setupTests.js
Fixes #30
We cannot naively merge the entry object, or we get unexpected behavior where the build fails because the index property does not resolve. This fixes the logic to only apply our default entry configuration object if none was present in the user-provided configuration argument.
=> Fix issue where entry is improperly merged with default

docs/changelog.md, src/presets.js
@rmccue caught that hot updates were failing on eslint errors, which is happening because the `emitWarning` option was not set in development. From [the `eslint-loader` documentation](https://www.npmjs.com/package/eslint-loader#emitwarning):
> [`eslint-loader`] Will always return warnings, if [`emitWarning`] option is set to true. **If you're using hot module replacement, you may wish to enable this in development, or else updates will be skipped when there's an eslint error.**
=> Set emitWarning: true in development for HMR

package.json
Fixing npm vulnerabilities by upgrading `serialize-javascript` to `^2.1.2`.
```
┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Cross-Site Scripting                                         │
├───────────────┼─────────────────────────────────────────────────────── …
```
=> Fixing npm vulnerabilities

src/plugins.js
As of 0.7.0, bundlename.LICENCE.txt files are generated if a specific set of comments are detected in the input bundles. As these files do not categorically represent the entire bundle, and were not generated in prior versions of the production factory, we should disable comment extraction for now and revisit whether we want to step into this feature mindfully in the future.
=> Disable Terser extractComments setting

src/presets.js
Using the `Webpack.Configuration` interface name as the type for the `options` parameter of the preset functions means you get property autocompletion and hints when writing out the config properties in a TypeScript-aware editor such as VS Code:
=> Add types for the preset function parameters and member variables

.eslintrc.js, docs/modules/loaders.md, docs/modules/presets.md, src/loaders.js, src/presets.js, src/presets.test.js
- Rename `options` to `config` in preset methods
- Refactor loader factory generation to wrap all loaders in a function which can optionally apply an injected filter callback to the computed loader before it is saved to the generated webpack configuration object.
- Modify presets functions to accept an options object as a second argument
- If a `filterLoaders` function is passed within this new preset options object, use that `filterLoaders` method to filter the computed output of each loader generated while executing the configuration preset.
- Document this new customization interface
=> Add loader filtering interface

docs/changelog.md, package.json, src/loaders.js
preset-env wraps autoprefixer and enables lower-config usage of new CSS features when a polyfill exists using conventional CSS (This is what create-react-app has migrated to under the hood)
=> Switch from autoprefixer to postcss-preset-env

docs/changelog.md, src/plugins.js
`plugins.copy()` now takes a sole object argument specifying a `patterns: []` array key, where before patterns were passed as a first argument.
See [the copy plugin's documentation](https://webpack.js.org/plugins/copy-webpack-plugin/#options) for more information.
=> Update CopyPlugin factory function signature to match updated dependency

src/helpers/with-dynamic-port.js, src/helpers/with-dynamic-port.test.js
Permit the `withDynamicPort` helper to work upon a [multi-config webpack setup](https://webpack.js.org/configuration/configuration-types/#exporting-multiple-configurations).
=> Support multiconfig in port helper

docs/changelog.md, src/plugins.js, src/plugins.test.js
`CleanPlugin` is undefined, causing `plugins.clean()` to trigger an error since v0.8.0. This corrects the import name to bring in the correct constructor.
=> Correct issue where clean plugin does not invoke a valid constructor

docs/modules/presets.md, src/loaders.js, src/presets.js, src/presets.test.js
There is not currently any good way to replace or act on the complete stylesheet loader chain, or to adjust any properties of the stylesheet loader object such as the `test` regex used to match files. This means that there's effectively no way to inject an alternative stylesheet preprocessor such as Stylus, nor can you (if you ever needed to) adjust the ordering of loaders or remove loaders from the chain.
This PR refactors the presets so that they now run the entire stylesheet loader chain through the same `filterLoaders` method, using the special loaderKey argument `stylesheet`. Documentation on the "overriding presets" page is updated to match.
=> Add support for filtering entire stylesheet loader chain

src/plugins.js
This is used in the file but was not exposed alongside the other plugins
=> Include OptimizeCssAssetsPlugin in plugins.constructors list

.eslintignore, .gitignore, .travis.yml, docs/guides/getting-started.md, package.json, test/.babelrc.js, test/src/helpers.js, test/src/index.js, test/src/style.scss, test/test-config.js
Following discussion around #147, @igmoweb & I determined we should add a notice to the "getting started" guide
Separately, in order to better validate the MVP functionality of this library, I determined it would be helpful to have a test build within the repo that would be run in CI to flag overtly breaking dependabot upgrades.
As both of these changes relate to the overall compatibility and stability of the library, I'm grouping them together here.
=> Add "smoke test" build to CI, and specify Webpack 4 in "getting started"

.eslintignore, docs/changelog.md, package.json
Bump all development depencies to their latest point releases, to ensure local environment is in sync with what will be installed if a user follows the "getting started" (and that dev-only components like Jest and ESLint are similarly up to date).
=> Update local development dependencies to latest versions.

docs/changelog.md, src/helpers/find-in-object.js, src/helpers/find-in-object.test.js, src/presets.js, src/presets.test.js
In a multiple-config Webpack setup, builds to two different output directories appear to both need a specified, unique publicPath in order for those bundles to be accessible as expected within the dev server.
To ensure that default usage creates bundles which can be loaded correctly in a multi-config DevServer environment, we adapt the value of output.path (stripping out the filePath cwd base) for use as a subdirectory within the in-memory virtual filesystem of the DevServer.
I encountered this behavior while testing v0.10-beta.1, and in a happy coincidence fixing it also fills in some of our `.todo` tests...
=> Use output.path when inferring publicPath

docs/changelog.md, src/helpers/infer-public-path.js, src/helpers/with-dynamic-port.js, src/helpers/with-dynamic-port.test.js, src/presets.js
This PR addresses #159.
Changes included:
- Abstract the logic to infer the public path based on the defined output path into a new function (and file), `inferPublicPath`.
- Use the new function in the `presets.development` factory.
- Use the new function in the `withDynamicPort` helper, and fix #159.
=> Abstract inferring publicPath, fix withDynamicPort

docs/changelog.md, package.json, src/presets.js, src/presets.test.js
This allows development presets to automatically share manifests, with the same logic production presets already use. Also adds tests for this behavior.
Largely this introduces nothing new: Just some modifications to a copy of the existing code to address dev-specific differences (i.e. inferred publicPath).
=> Port shared seed code from prod preset to dev

docs/changelog.md, package.json
The `run-parallel` package introduced in v1.2.0 a new dependency on `queue-microtask`, which is not written to support Node v10. Since v1.1.9 of `run-parallel` still satisfies the semver range of the library which depends upon the parallel execution (part of `copy-webpack-plugin`), pinning this dependency manually should restore Node v10 functionality.
=> Pin run-parallel library to avoid node v10 failure

docs/changelog.md, docs/guides/getting-started.md, package.json
Following up on discussion with @alwaysblank in Slack, there appears to be an incompatibility with Webpack Dev Server and Webpack CLI v4 where it will report errors or fail to start in some situations. Requiring v3 of the CLI library appears to resolve the issue.
This is arguably a breaking-enough change (it would show a peerDep error on `npm install` for a configured project that does use CLI v4) that we should ship a v0.11, but I've earmarked it for v0.10 for now. Thoughts?
=> Require webpack cli v3 to fix webpack-dev-server error

docs/changelog.md, src/plugins.js
When using the WebpackRTLPlugin the manifest doesn't produce entries for both the original and the RTL file. This results in the wrong file being loaded. This is caused by the fact that both files are in the same chunk.
There is an issue tracking this on the WebpackRTLPlugin: https://github.com/romainberger/webpack-rtl-plugin/issues/14
This commit includes a workaround. By providing a `map` function to the manifest plugin we can change the name when we're dealing with an RTL file. That results in two entries in the eventual manifest.
cc @kadamwhite, @alwaysblank
=> Fix handling of RTL files in the manifest

src/loaders.js
Potentially resolves as issue where autoprefixer arguments passed as comments are stripped and then ignored. 
Inspired by:
- https://github.com/symfony/webpack-encore/issues/638
- https://github.com/symfony/webpack-encore/pull/639
Since our CSS is compressed by other tools, we don't need sass to do it anyway.
=> Disable sass css compression to allow comments

docs/modules/loaders.md, docs/modules/presets.md, docs/reference.md, docs/reference/hooks.md, src/loaders.js, src/loaders.test.js, src/presets.js, src/presets.test.js
This PR targets the v1 branch (#205), and implements a change requested by @kucrut to permit filter callbacks to be aware of which configuration they are acting upon when called in the context of a preset factory.
=> Provide preset config as filter argument when appropriate

.github/workflows/deploy-docs.yml, docs/Gemfile
This PR hopefully fixes a bug we had where the new Just the HM Docs gem theme could not be found for the build and deploy action. If it works, we'll use the GitHub workflow action instead of the built in "deploy a branch" option.
=> Add workflow to deploy GH pages

.github/workflows/deploy-docs.yml, docs/Gemfile, docs/_config.yml
We updated Just the HM Docs to Jekyll 4 in https://github.com/humanmade/just-the-hm-docs/pull/11 so that we could inherit site variables from the theme config. 
This PR makes those updates to the gemfile and config, and adds a necessary `bundle install` step to the deploy action.
It also adds Front Matter layout defaults to the config file so that all markdown files don't need to specify a layout. This fixes a problem we found with Webpack Helpers not loading the theme properly if we removed the github-pages gem.
=> Update to Jekyll 4, inherit from theme
